# vim: set filetype=ruby

tap 'homebrew/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/services'

brew 'ack'
brew 'asdf'
brew 'bash-completion'
brew 'fzf'
brew 'git'
brew 'git-delta'
brew 'gpg2'
brew 'jq'
brew 'yq'
brew 'duti'
brew 'libsass'
brew 'libxml2'
brew 'rename'
brew 'ruby-build'
brew 'ssh-copy-id'
brew 'tree'
brew 'wget'

cask 'bitwarden'
cask 'docker'
cask 'dropbox'
cask 'firefox'
cask 'google-chrome'
cask 'iterm2'
cask 'java'
cask 'maccy'
cask 'rectangle'
cask 'slack'
cask 'visual-studio-code'
